checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  environment:
    python:
      version: 3.7.1
      virtualenv: true
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
